import { Client } from './types';

export const superAdminClients: Client[] = [
    {
        id: 'CLI-001',
        studioName: 'Pilates Flow - Moema',
        adminName: 'Ana Clara Souza',
        licenseStatus: 'Ativa',
        expiresAt: '15/01/2026',
        studentCount: 52,
        instructorCount: 4,
        mrr: 299.90,
    },
    {
        id: 'CLI-002',
        studioName: 'Studio Zen Pilates',
        adminName: 'Roberto Martins',
        licenseStatus: 'Teste',
        expiresAt: '28/12/2025',
        studentCount: 12,
        instructorCount: 2,
        mrr: 0,
    },
    {
        id: 'CLI-003',
        studioName: 'Corpo & Mente Pilates',
        adminName: 'Juliana Ferreira',
        licenseStatus: 'Ativa',
        expiresAt: '10/06/2026',
        studentCount: 89,
        instructorCount: 7,
        mrr: 299.90,
    },
    {
        id: 'CLI-004',
        studioName: 'Vitality Studio',
        adminName: 'Carlos Andrade',
        licenseStatus: 'Expirada',
        expiresAt: '01/11/2025',
        studentCount: 34,
        instructorCount: 3,
        mrr: 299.90,
    },
    {
        id: 'CLI-005',
        studioName: 'Studio Harmonia',
        adminName: 'Fernanda Lima',
        licenseStatus: 'Pendente',
        expiresAt: '12/12/2025',
        studentCount: 41,
        instructorCount: 4,
        mrr: 199.90,
    },
    {
        id: 'CLI-006',
        studioName: 'Pilates Premium',
        adminName: 'Gustavo Borges',
        licenseStatus: 'Ativa',
        expiresAt: '20/08/2026',
        studentCount: 120,
        instructorCount: 10,
        mrr: 499.90,
    },
];
